---
output: github_document
---

# lixingr

An R language wrapper for the lixinger API.

## User Guide

### Installation

```r
devtools::install_github('tanchangde/lixingr2')
```

### Configuration

-   Register and log in to lixinger, then acquire a `Token` from the [Open Platform](https://www.lixinger.com/open/api/token).

## Motivation

-   For creating reproducible, reusable, and version-controllable investment research reports.
-   To reduce repetitive data copying and pasting.

## Contributing Code

The commit logs for this project follow this [style guide](https://open.leancloud.cn/git-commit-message/). Please try to adhere to it. The optional scopes are:

- cn-company
- cn-index
- cn-industry
- cn-fund
- hk-company
- hk-index
- hk-industry
- us-index
- macro

## Why Choose lixinger

-   [Product, Code and Investment — Product Chapter](https://www.lixinger.com/marketing/about-us-product)
-   [Product, Code and Investment — Code Chapter](https://www.lixinger.com/marketing/about-us-coding)

## References

-   [knitr and Reproducible Statistical Research](https://cosx.org/2012/06/reproducible-research-with-knitr/)
-   [Lixinger Open Platform API Documentation](https://www.lixinger.com/open/api/doc)
